### ISSUE TITLE
`stdarg.h` not found by insights

### ISSUE THREAD

**Issue by pseyfert** [andreasfertig/cppinsights-docker#1]
# short version
running
```sh
echo "#include <string>\nint main() {return 0;}" | docker run -i cppinsights-trusty /usr/bin/insights -stdin x.cpp -- -std=c++17
```
outputs
```
In file included from x.cpp:1:
In file included from /usr/lib/gcc/x86_64-linux-gnu/7.4.0/../../../../include/c++/7.4.0/string:40:
In file included from /usr/lib/gcc/x86_64-linux-gnu/7.4.0/../../../../include/c++/7.4.0/bits/char_traits.h:40:
In file included from /usr/lib/gcc/x86_64-linux-gnu/7.4.0/../../../../include/c++/7.4.0/bits/postypes.h:40:
In file included from /usr/lib/gcc/x86_64-linux-gnu/7.4.0/../../../../include/c++/7.4.0/cwchar:44:
/usr/include/wchar.h:39:11: fatal error: 'stdarg.h' file not found
# include <stdarg.h>
          ^~~~~~~~~~
1 error generated.
Error while processing /x.cpp.
#include <string>
int main()
{
  return 0;
}

```

# long version

Basically I'm trying to run cppinsights on my code base and noticed that it can't process most files because standard headers are not found.
Similarly, `stddef.h` is missing when I try to include `<array>`.

Running `find` in the container I made a stab at manually adding an include path to the compiler's headers

```
/usr/lib/gcc/x86_64-linux-gnu/7/include
```

(slightly more complex example):

```
echo "#include <array>\nint main() {std::array x{1.f, 3.f, 5.f};return 0;}" | docker run -i cppinsights-trusty /usr/bin/insights -stdin x.cpp -- -std=c++17 -isystem/usr/lib/gcc/x86_64-linux-gnu/7/include
#include <array>
int main()
{
  std::array<float, 3> x = {{1.0f, 3.0f, 5.0f}};
  return 0;
}

```

which at least doesn't crash and looks correct but I'm suspicious if there's something wrong with the `insights` build that it doesn't find its headers? Or if I'm doing something absurdly wrong?

**Comment by andreasfertig** [comment]
Hello @pseyfert,

I forgot to update the Docker when the main project switched to Ubuntu 18.04 as build environment. I pushed an update, after a git pull and a make build it should work. If not, feel free to open the issue again.

Andreas

**Comment by pseyfert** [comment]
thanks for the fast response. I still see the issue.

To avoid mistakes on my side with updating I did:
```sh
cd path/to/cppinsights-docker
make clean
git pull
git log -1
> commit 9b3b6c18a5d4a5b219c9ea2ea84ca787b9f39915
> Author: Andreas Fertig <mail@cppinsights.io>
> Date:   Wed Mar 13 17:48:15 2019 +0100
> 
>     Updated Docker to Ubuntu 18.04 and use libstdc++-7 which is what Travis CI uses.
> 
# avoid picking up outdated container/images/layers
docker rm -f $(docker ps -q -f status=exited)
docker rmi -f $(docker images -q)
git status -u --ignored
> # On branch master
> nothing to commit, working directory clean
make
> 2019-03-13 18:16:17 (921 KB/s) - 'insights-ubuntu-14.04.tar.gz' saved [8358367/8358367]
> 
> tar -xzf insights-ubuntu-14.04.tar.gz
> docker build -t cppinsights-trusty `pwd`
> Sending build context to Docker daemon 31.47 MB
> Step 1/10 : FROM ubuntu:18.04
> Trying to pull repository docker.io/library/ubuntu ... 
> 18.04: Pulling from docker.io/library/ubuntu
> 898c46f3b1a1: Pull complete 
> 63366dfa0a50: Pull complete 
> 041d4cd74a92: Pull complete 
> 6e1bee0f8701: Pull complete 
> Digest: sha256:d019bdb3ad5af96fa1541f9465f070394c0daf0ffd692646983f491ce077b70f
> Status: Downloaded newer image for docker.io/ubuntu:18.04
>  ---> 94e814e2efa8
> Step 2/10 : LABEL maintainer "Andreas Fertig"
>  ---> Running in 4269f05d10f4
>  ---> b63140d04d56
> Removing intermediate container 4269f05d10f4
> Step 3/10 : RUN apt-get update && apt-get install -y --no-install-recommends libstdc++-7-dev
>  ---> Running in ae06a7642ff5
...
> Removing intermediate container b06a808f52e8
> Step 10/10 : CMD /run_in_docker.sh
>  ---> Running in 4da39872ee8a
>  ---> 86468b5dc812
> Removing intermediate container 4da39872ee8a
> Successfully built 86468b5dc812
md5sum insights
> 7cafce2aa43d56e9a91256aef0b0fd5a  insights
ls -l insights
> -rwxr-xr-x. 1 pseyfert z5 23038888 Mar  1 22:24 insights
```

Until here things look okay as far as I can tell, only the name of the tar ball looks a bit odd but as far as i understood the travis config of the main repo that's correct - I didn't see in the build logs on travis any indication how I can identify the binary so i post the md5sum here in case you have the right one at hand. The time stamp looks correct anyway.

Using the new created container as before gives me:

```sh
echo "#include <array>\nint main() {std::array x{1.f, 3.f, 5.f};return 0;}" | docker run -i cppinsights-trusty /usr/bin/insights -stdin x.cpp -- -std=c++17

> In file included from x.cpp:1:                                
> In file included from /usr/lib/gcc/x86_64-linux-gnu/7.3.0/../../../../include/c++/7.3.0/array:39:
> In file included from /usr/lib/gcc/x86_64-linux-gnu/7.3.0/../../../../include/c++/7.3.0/stdexcept:38:
> In file included from /usr/lib/gcc/x86_64-linux-gnu/7.3.0/../../../../include/c++/7.3.0/exception:142:
> In file included from /usr/lib/gcc/x86_64-linux-gnu/7.3.0/../../../../include/c++/7.3.0/bits/exception_ptr.h:38:
> /usr/lib/gcc/x86_64-linux-gnu/7.3.0/../../../../include/c++/7.3.0/bits/cxxabi_init_exception.h:38:10: fatal error: 'stddef.h' file not found
> #include <stddef.h>
>          ^~~~~~~~~~
> 1 error generated.
> #include <array>
> int main()
> {
>   std::array x;
>   return 0;
> }
> 
> Error while processing /x.cpp.

```

**Comment by andreasfertig** [comment]
Hello @pseyfert,

you're welcome. Thanks for the detailed description. It looks like there was still something missing. I just pushed another update. Unfortunately under macOS I cannot use `echo` like you do it. I pasted your code into a file `a.cpp`:

```
#include <array>

int main() {
    std::array x{1.f, 3.f, 5.f};
    return 0;
}
```

Then executed `a.cpp | docker run -i cppinsights-trusty /usr/bin/insights -stdin x.cpp -- -std=c++17` with the following result:

```
#include <array>

int main() {
    std::array x{1.f, 3.f, 5.f};
    return 0;
}
```

I hope this time the fix is a fix :-)

**Comment by pseyfert** [comment]
thanks again @andreasfertig, that looks good.

**Comment by andreasfertig** [comment]
Excellent! Happy insights :-)
